services:
  chatwoot_admin:
    image: nooviai/noovichat:4.7.0-beta
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    command: >
      sh -c "bundle exec rails db:chatwoot_prepare && bundle exec rails s -p 3000 -b 0.0.0.0"
    volumes:
      - chatwoot_storage:/app/storage
      - chatwoot_public:/app/public
      - chatwoot_mailer:/app/app/views/devise/mailer
      - chatwoot_mailers:/app/app/views/mailers
    networks:
      - network_swarm_public
    environment:
      - INSTALLATION_NAME=chatwoot
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - FRONTEND_URL=https://crm.${DOMINIO}
      - DEFAULT_LOCALE=en
      - ENABLE_PUSH_RELAY_SERVER=true
      - FORCE_SSL=true
      - ENABLE_ACCOUNT_SIGNUP=false
      - RAILS_LOG_TO_STDOUT=true
      - USE_INBOX_AVATAR_FOR_BOT=true
      - REDIS_URL=redis://redis_cw:6380
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=cwdb
      - MAILER_SENDER_EMAIL=${MAILER_SENDER_EMAIL}
      - SMTP_ADDRESS=${SMTP_ADDRESS}
      - SMTP_AUTHENTICATION=plain
      - SMTP_DOMAIN=${SMTP_DOMAIN}
      - SMTP_ENABLE_STARTTLS_AUTO=false
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - ACTIVE_STORAGE_SERVICE=s3_compatible
      - STORAGE_BUCKET_NAME=chatwoot
      - STORAGE_ACCESS_KEY_ID=${STORAGE_ACCESS_KEY_ID}
      - STORAGE_SECRET_ACCESS_KEY=${STORAGE_SECRET_ACCESS_KEY}
      - STORAGE_REGION=nyc3
      - STORAGE_ENDPOINT=https://s3storage.${DOMINIO}
      - STORAGE_FORCE_PATH_STYLE=true
      - NOOVI_LICENSE_KEY=NOOVI-ERIEZ-JH8HS-V45DI-RW6K5
      - NOOVI_CUSTOMER_ID=CUST-ZOF-7L
      - NOOVI_API_KEY=nai_tR0qSbls7gwuvS1wH4rCWxs3jPpehD
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.chatwoot_admin.rule=Host(`crm.${DOMINIO}`)
        - traefik.http.routers.chatwoot_admin.entrypoints=websecure
        - traefik.http.routers.chatwoot_admin.tls.certresolver=letsencryptresolver
        - traefik.http.routers.chatwoot_admin.service=chatwoot_admin
        - traefik.http.services.chatwoot_admin.loadbalancer.server.port=3000
        - traefik.http.services.chatwoot_admin.loadbalancer.passhostheader=true
        - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
        - traefik.http.routers.chatwoot_admin.middlewares=sslheader
volumes:
  chatwoot_storage:
    external: true
    name: chatwoot_storage
  chatwoot_public:
    external: true
    name: chatwoot_public
  chatwoot_mailer:
    external: true
    name: chatwoot_mailer
  chatwoot_mailers:
    external: true
    name: chatwoot_mailers
networks:
  network_swarm_public:
    external: true
    name: network_swarm_public
