services:
  waha:
    image: devlikeapro/waha-plus:latest
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    networks:
      - network_swarm_public
    environment:
      - PORT=3000
      - WHATSAPP_API_HOSTNAME=wapi.${DOMINIO}
      - WHATSAPP_API_SCHEMA=https
      - WAHA_BASE_URL=https://wapi.${DOMINIO}
      - WAHA_PRESENCE_AUTO_ONLINE=True
      - WAHA_PRESENCE_AUTO_ONLINE_DURATION_SECONDS=25
      - TZ=America/Sao_Paulo
      - WAHA_API_KEY_PLAIN=${WAHA_API_KEY_PLAIN}
      - WAHA_API_KEY=sha512:${WAHA_API_KEY_PLAIN_SHA512}
      - WHATSAPP_SESSIONS_POSTGRESQL_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/wahadb?sslmode=disable
      - WAHA_DASHBOARD_USERNAME=${WAHA_DASHBOARD_USERNAME}
      - WAHA_DASHBOARD_PASSWORD=${WAHA_DASHBOARD_PASSWORD}
      - WHATSAPP_SWAGGER_ENABLED=true
      - WHATSAPP_SWAGGER_USERNAME=${WAHA_DASHBOARD_USERNAME}
      - WHATSAPP_SWAGGER_PASSWORD=${WAHA_DASHBOARD_PASSWORD}
      - WAHA_RESTART_ALL_SESSIONS=true
      - WAHA_AUTO_START_DELAY_SECONDS=5
      - WAHA_APPS_ENABLED=true
      - WHATSAPP_DEFAULT_ENGINE=GOWS
      - REDIS_URL=redis://6_redis_waha_redis_waha:6382
      - WAHA_APPS_JOBS_CONCURRENCY=5
      - WAHA_APPS_JOBS_REMOVE_ON_COMPLETE_AGE=259200
      - WAHA_APPS_JOBS_REMOVE_ON_COMPLETE_COUNT=1000
      - WAHA_APPS_JOBS_REMOVE_ON_FAIL_AGE=2678400
      - WAHA_APPS_JOBS_REMOVE_ON_FAIL_COUNT=1000
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.waha.rule=Host(`wapi.${DOMINIO}`)
        - traefik.http.routers.waha.entrypoints=websecure
        - traefik.http.routers.waha.tls.certresolver=letsencryptresolver
        - traefik.http.routers.waha.service=waha
        - traefik.http.services.waha.loadbalancer.server.port=3000
        - traefik.http.services.waha.loadbalancer.passhostheader=true
        - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
        - traefik.http.routers.waha.middlewares=sslheader
networks:
  network_swarm_public:
    external: true
    name: network_swarm_public