services:
  postgres:
    image: ${POSTGRES_IMAGE}
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    networks:
      - network_swarm_public
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1.5"
          memory: 2048M
volumes:
  postgres_data:
    external: true
    name: postgres_data
  postgres_init:
    external: true
    name: postgres_init
networks:
  network_swarm_public:
    external: true
    name: network_swarm_public